/*
 * This is proprietary code written by Syahilan A/L Selvarajoo [TP062031] & Darshini Dakshyani Beerachee [TP060519]
 * APD2F2109CS(DA) || CT038-3-2-OODJ-LAB-18
 */
package assignmentoodj;

import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButtonMenuItem;

public class PersonnelUserManagementPage extends JFrame{
    
    // Variables declaration                 
    private JButton AddPeopleBut;
    private JButton AddPersonnelBut;
    private JRadioButtonMenuItem PersonnelUserManagementPage;
    private JButton BackBut;
    private JButton DispPeopleBut;
    private JButton DispPersonnelBut;
    private JButton EditPeopleBut;
    private JButton EditPersonnelBut;
    private JButton SearPeopleIdBut;
    private JButton SearPersonnelIdBut;
    private JButton RemPeopleBut;
    private JButton RemPersonnelBut;
    private ButtonGroup buttonGroup1;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    // End of variables declaration               
    
    public PersonnelUserManagementPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        PersonnelUserManagementPage = new JRadioButtonMenuItem();
        BackBut = new JButton();
        jLabel1 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        AddPeopleBut = new JButton();
        AddPersonnelBut = new JButton();
        jLabel5 = new JLabel();
        DispPeopleBut = new JButton();
        DispPersonnelBut = new JButton();
        jLabel6 = new JLabel();
        SearPeopleIdBut = new JButton();
        SearPersonnelIdBut = new JButton();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        EditPeopleBut = new JButton();
        EditPersonnelBut = new JButton();
        RemPeopleBut = new JButton();
        RemPersonnelBut = new JButton();

        PersonnelUserManagementPage.setForeground(new java.awt.Color(255, 0, 0));
        PersonnelUserManagementPage.setSelected(true);
        PersonnelUserManagementPage.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("COVID-19 VACCINE REGISTRATION SYSTEM");
        setLocationByPlatform(true);
        setResizable(false);
        setName("PersonnelUserManagementPage"); // NOI18N

        BackBut.setBackground(new java.awt.Color(255, 0, 0));
        BackBut.setFont(new java.awt.Font("Sans Serif", 3, 12)); // NOI18N
        BackBut.setText("<<BACK");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sans Serif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("User Management Page");

        jLabel3.setFont(new java.awt.Font("Sans Serif", 1, 20)); // NOI18N
        jLabel3.setText("Please select from the options:");

        jLabel4.setFont(new java.awt.Font("Sans Serif", 2, 16)); // NOI18N
        jLabel4.setText("Add new users by type:");

        AddPeopleBut.setFont(new java.awt.Font("Sans Serif", 0, 13)); // NOI18N
        AddPeopleBut.setText("People");
        AddPeopleBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPeopleButActionPerformed(evt);
            }
        });

        AddPersonnelBut.setFont(new java.awt.Font("Sans Serif", 0, 13)); // NOI18N
        AddPersonnelBut.setText("Personnel");
        AddPersonnelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPersonnelButActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Sans Serif", 2, 16)); // NOI18N
        jLabel5.setText("Display all Records of");

        DispPeopleBut.setFont(new java.awt.Font("Sans Serif", 0, 13)); // NOI18N
        DispPeopleBut.setText("People");
        DispPeopleBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispPeopleButActionPerformed(evt);
            }
        });

        DispPersonnelBut.setFont(new java.awt.Font("Sans Serif", 0, 13)); // NOI18N
        DispPersonnelBut.setText("Personnel");
        DispPersonnelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispPersonnelButActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sans Serif", 2, 16)); // NOI18N
        jLabel6.setText("Search Users by ID");

        SearPeopleIdBut.setFont(new java.awt.Font("Sans Serif", 0, 13)); // NOI18N
        SearPeopleIdBut.setText("People by ID");
        SearPeopleIdBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearPeopleIdButActionPerformed(evt);
            }
        });

        SearPersonnelIdBut.setFont(new java.awt.Font("Sans Serif", 0, 13)); // NOI18N
        SearPersonnelIdBut.setText("Personnel by ID");
        SearPersonnelIdBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearPersonnelIdButActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sans Serif", 2, 16)); // NOI18N
        jLabel7.setText("Edit Existing Users");

        jLabel8.setFont(new java.awt.Font("Sans Serif", 2, 16)); // NOI18N
        jLabel8.setText("Remove user");

        EditPeopleBut.setFont(new java.awt.Font("Sans Serif", 0, 13)); // NOI18N
        EditPeopleBut.setText("People");
        EditPeopleBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPeopleButActionPerformed(evt);
            }
        });

        EditPersonnelBut.setFont(new java.awt.Font("Sans Serif", 0, 13)); // NOI18N
        EditPersonnelBut.setText("Personnel");
        EditPersonnelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPersonnelButActionPerformed(evt);
            }
        });

        RemPeopleBut.setFont(new java.awt.Font("Sans Serif", 0, 13)); // NOI18N
        RemPeopleBut.setText("People");
        RemPeopleBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemPeopleBut1ActionPerformed(evt);
            }
        });

        RemPersonnelBut.setFont(new java.awt.Font("Sans Serif", 0, 13)); // NOI18N
        RemPersonnelBut.setText("Personnel");
        RemPersonnelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemPersonnelBut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(BackBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DispPeopleBut)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DispPersonnelBut))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AddPeopleBut)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AddPersonnelBut)))
                                .addGap(220, 220, 220))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RemPersonnelBut)
                                    .addComponent(SearPersonnelIdBut)
                                    .addComponent(EditPersonnelBut))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SearPeopleIdBut)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(RemPeopleBut)
                    .addComponent(jLabel8)
                    .addComponent(EditPeopleBut))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackBut)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddPersonnelBut)
                    .addComponent(AddPeopleBut))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DispPersonnelBut)
                    .addComponent(DispPeopleBut))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearPeopleIdBut)
                    .addComponent(SearPersonnelIdBut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemPeopleBut)
                    .addComponent(RemPersonnelBut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditPeopleBut)
                    .addComponent(EditPersonnelBut))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {                                        
        this.setVisible(false);
        PersonnelMainPage pmpA = new PersonnelMainPage();
        pmpA.setVisible(true);
    }                                                                    

    
    private void AddPeopleButActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.setVisible(false);
        PersonnelAddPeoplePage papp = new PersonnelAddPeoplePage();
        papp.setVisible(true);
    }      
    
    
    private void AddPersonnelButActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.setVisible(false);
        PersonnelAddPersonnelPage pappA = new PersonnelAddPersonnelPage();
        pappA.setVisible(true);
        
    }

    
    private void DispPeopleButActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.setVisible(false);
        PersonnelManagePeoplePage pmppA = new PersonnelManagePeoplePage();
        pmppA.setVisible(true);
    }                                           

    
    private void DispPersonnelButActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.setVisible(false);
        
    }   
    
    
    private void EditPeopleButActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.setVisible(false);
        
    }        
    
    
    private void EditPersonnelButActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.setVisible(false);
        
    } 
    
    
    private void SearPeopleIdButActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.setVisible(false);
        
    }    
    
    private void SearPersonnelIdButActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.setVisible(false);
        
    } 

    private void RemPeopleBut1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.setVisible(false);
        
    } 
    
    private void RemPersonnelBut1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.setVisible(false);
        
    } 
    

        

    private static class AdminModifySport {

        public AdminModifySport() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
    
    
    
}
