/*
 * This is proprietary code written by Syahilan A/L Selvarajoo [TP062031] & Darshini Dakshyani Beerachee [TP060519]
 * APD2F2109CS(DA) || CT038-3-2-OODJ-LAB-18
 */
package assignmentoodj;

import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButtonMenuItem;

public class PersonnelUserManagementPage extends JFrame {

    // Variables declaration                 
    private JButton AddPeopleBut;
    private JButton AddPersonnelBut;
    private JRadioButtonMenuItem PersonnelUserManagementPage;
    private JButton BackBut;
    private JButton DispPeopleBut;
    private JButton DispPersonnelBut;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    // End of variables declaration               

    public PersonnelUserManagementPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        PersonnelUserManagementPage = new javax.swing.JRadioButtonMenuItem();
        BackBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddPeopleBut = new javax.swing.JButton();
        AddPersonnelBut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DispPeopleBut = new javax.swing.JButton();
        DispPersonnelBut = new javax.swing.JButton();

        PersonnelUserManagementPage.setForeground(new java.awt.Color(255, 0, 0));
        PersonnelUserManagementPage.setSelected(true);
        PersonnelUserManagementPage.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COVID-19 VACCINE REGISTRATION SYSTEM");
        setName("PersonnelUserManagementPage");

        BackBut.setBackground(new java.awt.Color(255, 0, 0));
        BackBut.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        BackBut.setForeground(new java.awt.Color(255, 255, 255));
        BackBut.setText("<<BACK");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("User Management Page");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel3.setText("Please choose the function");

        jLabel4.setFont(new java.awt.Font("SansSerif", 2, 16)); // NOI18N
        jLabel4.setText("Add new Users:");

        AddPeopleBut.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        AddPeopleBut.setText("People");
        AddPeopleBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPeopleButActionPerformed(evt);
            }
        });

        AddPersonnelBut.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        AddPersonnelBut.setText("Personnel");
        AddPersonnelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPersonnelButActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 2, 16)); // NOI18N
        jLabel5.setText("Manage Existing Users:");

        DispPeopleBut.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        DispPeopleBut.setText("People");
        DispPeopleBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispPeopleButActionPerformed(evt);
            }
        });

        DispPersonnelBut.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        DispPersonnelBut.setText("Personnel");
        DispPersonnelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispPersonnelButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(AddPeopleBut)
                                                .addGap(38, 38, 38)
                                                .addComponent(AddPersonnelBut))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(DispPeopleBut)
                                                .addGap(38, 38, 38)
                                                .addComponent(DispPersonnelBut)))
                                .addGap(68, 192, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(BackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BackBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AddPersonnelBut)
                                        .addComponent(AddPeopleBut))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DispPersonnelBut)
                                        .addComponent(DispPeopleBut))
                                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        PersonnelMainPage pmpA = new PersonnelMainPage();
        pmpA.setVisible(true);
    }

    private void AddPeopleButActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        PersonnelAddPeoplePage papp = new PersonnelAddPeoplePage();
        papp.setVisible(true);
    }

    private void AddPersonnelButActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        PersonnelAddPersonnelPage pappA = new PersonnelAddPersonnelPage();
        pappA.setVisible(true);

    }

    private void DispPeopleButActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        PersonnelManagePeoplePage pmppA = new PersonnelManagePeoplePage();
        pmppA.setVisible(true);
    }

    private void DispPersonnelButActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        PersonnelManagePersonnelPage pmppB = new PersonnelManagePersonnelPage();
        pmppB.setVisible(true);

    }

}
